//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/Scenes/Alan/PlayerTouchMovement/Input/InputActionLeftStick.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputActionLeftStick: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputActionLeftStick()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputActionLeftStick"",
    ""maps"": [
        {
            ""name"": ""LeftStick"",
            ""id"": ""a8f37c9b-79c9-4589-8a81-55acd70846bd"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""6e821853-649b-4123-8b65-a90351e8c590"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""c8b074bd-f3fc-4212-a01a-e944aac71564"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // LeftStick
        m_LeftStick = asset.FindActionMap("LeftStick", throwIfNotFound: true);
        m_LeftStick_Move = m_LeftStick.FindAction("Move", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // LeftStick
    private readonly InputActionMap m_LeftStick;
    private List<ILeftStickActions> m_LeftStickActionsCallbackInterfaces = new List<ILeftStickActions>();
    private readonly InputAction m_LeftStick_Move;
    public struct LeftStickActions
    {
        private @InputActionLeftStick m_Wrapper;
        public LeftStickActions(@InputActionLeftStick wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_LeftStick_Move;
        public InputActionMap Get() { return m_Wrapper.m_LeftStick; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(LeftStickActions set) { return set.Get(); }
        public void AddCallbacks(ILeftStickActions instance)
        {
            if (instance == null || m_Wrapper.m_LeftStickActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_LeftStickActionsCallbackInterfaces.Add(instance);
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
        }

        private void UnregisterCallbacks(ILeftStickActions instance)
        {
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
        }

        public void RemoveCallbacks(ILeftStickActions instance)
        {
            if (m_Wrapper.m_LeftStickActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ILeftStickActions instance)
        {
            foreach (var item in m_Wrapper.m_LeftStickActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_LeftStickActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public LeftStickActions @LeftStick => new LeftStickActions(this);
    public interface ILeftStickActions
    {
        void OnMove(InputAction.CallbackContext context);
    }
}
